version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr_flask_app
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - TZ=Asia/Riyadh
    networks:
      - hr_network
    restart: always

networks:
  hr_network:
    external: true