"""Initial migration

Revision ID: 675bd415cf71
Revises: 
Create Date: 2025-03-05 20:47:04.198882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675bd415cf71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_name', sa.String(length=100), nullable=False),
    sa.Column('allowed_break_time', sa.String(length=5), nullable=True),
    sa.Column('overtime_hour_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delay_minute_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('production_system', sa.Boolean(), nullable=False),
    sa.Column('shift_system', sa.Boolean(), nullable=False),
    sa.Column('month_system', sa.Boolean(), nullable=False),
    sa.Column('production_piece_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_pieces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('piece_number', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('piece_name', sa.String(length=255), nullable=False),
    sa.Column('price_levels', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('piece_number')
    )
    op.create_table('professions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('allowed_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('allowed_exit_minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('absence_minutes', sa.Integer(), nullable=False),
    sa.Column('extra_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('employee_type', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('advancePercentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('certificates', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=255), nullable=True),
    sa.Column('id_card_number', sa.String(length=50), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('residence', sa.String(length=255), nullable=True),
    sa.Column('mobile_1', sa.String(length=15), nullable=True),
    sa.Column('mobile_2', sa.String(length=15), nullable=True),
    sa.Column('mobile_3', sa.String(length=15), nullable=True),
    sa.Column('worker_agreement', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('work_system', sa.String(length=100), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('profession_id', sa.Integer(), nullable=True),
    sa.Column('insurance_deduction', sa.Float(), nullable=True),
    sa.Column('allowances', sa.Float(), nullable=True),
    sa.Column('insurance_start_date', sa.Date(), nullable=True),
    sa.Column('insurance_end_date', sa.Date(), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position'], ['job_titles.id'], ),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.Date(), nullable=True),
    sa.Column('checkInTime', sa.Time(), nullable=True),
    sa.Column('checkOutTime', sa.Time(), nullable=True),
    sa.Column('checkInReason', sa.String(length=255), nullable=True),
    sa.Column('checkOutReason', sa.String(length=255), nullable=True),
    sa.Column('productionQuantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empId'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('attendance_type', sa.Enum('FULL_DAY', 'HALF_DAY', 'ONLINE_DAY', 'ABSENT', name='attendancetype'), nullable=False),
    sa.Column('is_excused_absence', sa.Boolean(), nullable=True),
    sa.Column('excuse_document', sa.String(length=255), nullable=True),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='unique_employee_date')
    )
    op.create_table('production_monitoring',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quality_grade', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['production_pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_monitoring')
    op.drop_table('monthly_attendance')
    op.drop_table('attendances')
    op.drop_table('advances')
    op.drop_table('employees')
    op.drop_table('user')
    op.drop_table('shift')
    op.drop_table('professions')
    op.drop_table('production_pieces')
    op.drop_table('job_titles')
    # ### end Alembic commands ###
