"""add feiled

Revision ID: aa779514e728
Revises: 0c05dfd1bcaa
Create Date: 2025-02-26 12:04:01.818927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa779514e728'
down_revision = '0c05dfd1bcaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkInReason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('checkOutReason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('productionQuantity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('productionQuantity')
        batch_op.drop_column('checkOutReason')
        batch_op.drop_column('checkInReason')

    # ### end Alembic commands ###
