"""rewards

Revision ID: cee4e2d92145
Revises: 675bd415cf71
Create Date: 2025-04-20 14:49:17.638330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee4e2d92145'
down_revision = '675bd415cf71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('attendance_types')
    with op.batch_alter_table('professions', schema=None) as batch_op:
        batch_op.drop_column('daily_rate')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hourly_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daily_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))

    op.create_table('attendance_types',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=8, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__attendan__3213E83F8F356DCA')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__user__3213E83F507F64E0')
    )
    # ### end Alembic commands ###
