"""add

Revision ID: cfe9b7d77d69
Revises: aa779514e728
Create Date: 2025-03-05 08:39:52.120375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe9b7d77d69'
down_revision = 'aa779514e728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('insurance_end_date', sa.Date(), nullable=True))
        batch_op.alter_column('insurance_deduction',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('allowances',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('allowances',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('insurance_deduction',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.drop_column('insurance_end_date')
        batch_op.drop_column('insurance_start_date')

    # ### end Alembic commands ###
