"""add

Revision ID: e233acd71f75
Revises: cfe9b7d77d69
Create Date: 2025-03-05 09:27:39.492560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e233acd71f75'
down_revision = 'cfe9b7d77d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_pieces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_pieces', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
