"""rewards

Revision ID: f5ec9329847b
Revises: e233acd71f75
Create Date: 2025-04-20 11:02:42.405796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ec9329847b'
down_revision = 'e233acd71f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penalties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    with op.batch_alter_table('professions', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('daily_rate')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daily_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hourly_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True))

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__user__3213E83FBBD19BFF')
    )
    op.drop_table('rewards')
    op.drop_table('penalties')
    # ### end Alembic commands ###
